import type { NextPage } from "next";
import Head from "next/head";
import { AiOutlineCaretDown } from "react-icons/ai";

const AddQuestions: NextPage = () => {
  return (
    <>
      <Head>
        <title>Add Questions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="content_container">
        <div className="header">
          <h3>Question For Mock Up Test </h3>
          <small>Create Question</small>
        </div>
        <div className="form">
          <form>
            <div className="form_items select_category">
              <label htmlFor="catgry_select">Select Category</label>
              <div className="dropdown_select">
                <select id="catgry_select">
                  <option value=""> Select Category</option>
                  <option value=""> BCA</option>
                  <option value=""> Bsc.CSIT</option>
                </select>
                <AiOutlineCaretDown className="select_downArrow" />
              </div>
            </div>
            <div className="form_items question_form">
              <input type="text" placeholder="Question"></input>
            </div>
            <div className="answer">
              <div className="form_items_row">
                <label htmlFor="a">A</label>
                <input type="text" id="a"></input>
              </div>
              <div className="form_items_row">
                <label htmlFor="b">B</label>
                <input type="text" id="b"></input>
              </div>
              <div className="form_items_row">
                <label htmlFor="c">C</label>
                <input type="text" id="c"></input>
              </div>
              <div className="form_items_row">
                <label htmlFor="d">D</label>
                <input type="text" id="d"></input>
              </div>
            </div>
            <div className="correct_answer">
              <div className="form_items">
                <label htmlFor="catgry_select">Select Correct Answer</label>
                <div className="dropdown_select">
                  <select id="catgry_select">
                    <option value=""> Select Correct Answer</option>
                    <option value="a"> A</option>
                    <option value="b"> B</option>
                    <option value="c"> C</option>
                    <option value="d"> D</option>
                  </select>
                  <AiOutlineCaretDown className="select_downArrow" />
                </div>
              </div>
            </div>
            <button type="submit">Create New</button>
          </form>
        </div>
      </div>
    </>
  );
};

export default AddQuestions;
